name: CI/CD DevSecops Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'Tic-Tac-Toe-DevSecOps-Project/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'Tic-Tac-Toe-DevSecOps-Project/**'


jobs:
  test:
    if: github.actor != 'github-actions[bot]'
    name: Unit Testing
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Tic-Tac-Toe-DevSecOps-Project

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Tic-Tac-Toe-DevSecOps-Project/package-lock.json
      
      - name: Install Dependencies 
        run: npm ci 

      - name: Run tests
        run: npm test || echo "No tests found"

  lint:
    if: github.actor != 'github-actions[bot]'
    name: Static Code Analysis
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: Tic-Tac-Toe-DevSecOps-Project
    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Tic-Tac-Toe-DevSecOps-Project/package-lock.json

      - name: install dependencies
        run: npm ci 

      - name: Run ESLint
        run: npm run lint

  build: 
    if: github.actor != 'github-actions[bot]'
    name: Build Stage
    runs-on: ubuntu-latest
    needs: [test, lint]
    defaults:
      run:
        working-directory: Tic-Tac-Toe-DevSecOps-Project
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Tic-Tac-Toe-DevSecOps-Project/package-lock.json

      - name: install Dependencies
        run: npm ci  

      - name: Build project
        run: npm run build

      - name: Upload Build artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: build-artifacts
          path: Tic-Tac-Toe-DevSecOps-Project/dist/

  docker:
    if: github.actor != 'github-actions[bot]'
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: [ build ]  
    defaults:
      run:
        working-directory: Tic-Tac-Toe-DevSecOps-Project

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Convert repo name to lowercase
        id: vars
        run: echo "repo_lower=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Download build artifacts
        uses: actions/download-artifact@v4 
        with:
          name: build-artifacts
          path: dist/

      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Registry
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Extract MetaData for Docker
        id: meta
        uses: docker/metadata-action@v5 
        with: 
          images: ghcr.io/${{ steps.vars.outputs.repo_lower }}
          tags: | 
            type=sha,
            latest
      
      - name: Extract SHA tag only
        id: trim
        run: |
          echo "sha_tag=$(echo '${{ steps.meta.outputs.tags }}' | tr ',' '\n' | grep 'sha-')" >> $GITHUB_OUTPUT

      - name : Build Docker image
        uses: docker/build-push-action@v5
        with: 
          context: Tic-Tac-Toe-DevSecOps-Project
          file: Tic-Tac-Toe-DevSecOps-Project/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with: 
          image-ref: ${{ steps.trim.outputs.sha_tag }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.lab }}
          
      - name: Set Image tag output
        id: set_output
        run: echo "image_tag=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

  update-k8s:
    name: Update Kubernetes Deployment
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && github.actor != 'github-actions[bot]'
    defaults:
      run:
        working-directory: Tic-Tac-Toe-DevSecOps-Project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      - name: Setup Git config
        run: |
          git config user.name "Github Actions"
          git config user.email "actions@github.com"
      
      - name: Update Kubernetes Deplyment file
        env: 
          IMAGE_TAG: sha-${{ github.sha }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          REGISTRY: ghcr.io
        run: |
          NEW_IMAGE="${REGISTRY}/${GITHUB_REPOSITORY}:${IMAGE_TAG}"
          sed -i "s|image: ${REGISTRY}/.*|image: ${NEW_IMAGE}|g" kubernetes/deployment.yaml
          echo "Updated deployment to use image: ${NEW_IMAGE}"
          grep -A 1 "image:" kubernetes/deployment.yaml

      - name: Commit and push changes
        run: |
          git add kubernetes/deployment.yaml
          git commit -m "Updated k8 deployment with images tag : ${{ needs.docker.outputs.image_tag }} [skip ci] " || echo "No Changes to commit"    
          git push
          
  notify_failure:
    needs: [test, lint, build, docker, update-k8s]
    if: failure()
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Tic-Tac-Toe-DevSecOps-Project

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Collect failure logs
        run: |
          echo "${{ toJson(needs) }}" > full_errors.json
          tail -n 200 full_errors.json > short_errors.txt
          echo "=== Extracting error lines ==="
          grep -Ri "error" -n full_errors.json > error_lines_only.txt || true

      - name: Send logs to AI for analysis
        id: gemini
        run: |
          CONTENT=$(cat errors.json | sed 's/"/\\"/g')

          RESPONSE=$(curl -s "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent" \
            -H "x-goog-api-key: ${{ secrets.GEMINI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -X POST \
            -d "{
                  \"contents\": [{
                    \"parts\": [{
                      \"text\": \"You are a senior DevOps engineer. A GitHub Actions workflow failed. Explain the error in simple human-like language in short and give clear steps to fix it.\n\nHere is the raw failure log:\n\n${CONTENT}\"
                    }]
                  }]
                }")

          echo "$RESPONSE" > gemini_output.json

      - name: Print AI Failure Summary in Actions UI
        run: |
          SUMMARY=$(cat gemini_output.json | jq -r '.candidates[0].content.parts[0].text')
          echo "::group:: AI Failure Analysis"
          echo "$SUMMARY"
          echo "::endgroup::"
          echo "::notice::Gemini Summary: $SUMMARY"

